global_map_server:
  globalmap_pcd: "/home/WorkSpace/src/hdl_localization/data/map_wuxi.pcd"
  convert_utm_to_local: false
  downsample_resolution: 0.1

hdl_loc:
  robot_odom_frame_id: "odom"
  odom_child_frame_id: "ouster"
  globalmap_frame_id: "map"
  use_imu: false
  invert_acc: false
  invert_gyro: false
  reg_method: "NDT_OMP"
  ndt_neighbor_search_method: "DIRECT7"
  ndt_neighbor_search_radius: 2.0
  ndt_resolution: 1.0
  downsample_resolution_scan: 0.1
  specify_init_pose: true
  init_pos_x: 0.0
  init_pos_y: 0.0
  init_pos_z: 0.0
  init_ori_w: 0.383
  init_ori_x: 0.0
  init_ori_y: 0.0
  init_ori_z: -0.924

  imu_ext_rot: [1, 0, 0, 0, -1, 0, 0, 0, -1]
  imu_ext_pos: [0.065, 0.025, -0.18]

  cool_time_duration: 2.0
  enable_robot_odometry_prediction: false
  status_max_correspondence_dist: 0.5
  status_max_valid_point_dist: 25.0